### ISSUE TITLE
fcntl substitute for Windows

### ISSUE THREAD

**Issue by AMuntzinger** [menzHSE/cv-ml-lecture-notebooks#8]
The fcntl module is not available on Windows, maybe the dependency can be resolved?

**Comment by menzHSE** [comment]
Any idea where the dependency comes from? I have no access to a Windows machine :(

**Comment by AMuntzinger** [comment]
Yes, it is used in nbutils/exec.py. Not sure if anywhere else though!

**Comment by menzHSE** [comment]
Ah yes! It seems to be necessary for colab only. Can you remove the import and the whole ```executeCaptureColabCommand(command)``` function in ```exec.py``` on your local setup? If that works, I will condition the import on the platform.

**Comment by menzHSE** [comment]
Might be fixed by #9. @AMuntzinger Can you please check and confirm?

**Comment by AMuntzinger** [comment]
Yes, that solves the problem :-)

**Comment by menzHSE** [comment]
Fixed by #9.
